//! `AttestationRecordV2` — normative signed binary form with full
//! trust-provider, keyring-epoch, and rollback binding (RFC v0.3-004).
//!
//! The v2 canonical digest covers every trust-relevant field under the
//! `"FJELL-ATTEST-V2"` domain separator so a single signature check
//! suffices for complete local-trust validation.

use fjell_canon::{BufSink, Canon};
use fjell_measure_format::Digest32;
// KeyEpoch imported only when key-epoch validation tests are added (v0.8).
// use fjell_keyring::KeyEpoch;
use fjell_trust_provider::ids::TrustProviderId;
use fjell_trust_provider::material::{AttestationDigest, Signature};
use fjell_trust_provider::profile::{TrustProfile, TrustProviderKind};
use fjell_trust_provider::provider::HardwareTrustProvider;
use fjell_upgrade_format::rollback_record::AdvanceSource;

use crate::{
    AttestationProfile, AttestationRecordId, BootClaims, HealthClaims, MeasurementClaims,
    ProvenanceClaims, SnapshotClaims, VerificationClaims,
};

// ── Domain separator ─────────────────────────────────────────────────────────

pub const ATTEST_V2_DOMAIN: &[u8] = b"FJELL-ATTEST-V2";

/// Capacity of the canonical stream (it is well under this; overrunning it
/// panics in `BufSink`, so a field added without widening it fails loudly).
const ATTEST_V2_STREAM_MAX: usize = 512;

// ── New claim structs ────────────────────────────────────────────────────────

/// Trust-provider claims bound into every v2 record.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub struct ProviderClaims {
    pub provider_id: TrustProviderId,
    /// Raw tag of `TrustProviderKind`.
    pub provider_kind: u8,
    /// Raw tag of `TrustProfile`.
    pub profile_tag: u8,
    pub provider_generation: u16,
}

/// Keyring epoch claims bound into every v2 record.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub struct KeyringClaims {
    /// Active anchor epoch for `AttestationSigning` at signing time.
    pub active_epoch_attestation: u32,
    /// Active anchor epoch for `ReleaseVerification` at signing time.
    pub active_epoch_release: u32,
    /// Active anchor epoch for `PolicyVerification` at signing time.
    pub active_epoch_policy: u32,
    /// SHA-256 of the canonical keyring snapshot encoding (RFC v0.3-002).
    pub keyring_snapshot_digest: Digest32,
}

/// Anti-rollback state claims.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub struct RollbackClaims {
    /// Primary channel for which the floor is reported.
    pub channel_id: [u8; 8],
    pub min_counter: u64,
    /// Raw `AdvanceSource` tag of the last advance.
    pub last_advance_source: u8,
    /// Whether `trust_provider.read_anti_rollback_counter()` succeeded.
    pub trust_provider_counter_supported: bool,
    pub trust_provider_counter_value: u64,
}

/// Nonce classification — how the freshness nonce was obtained.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
#[repr(u8)]
pub enum NonceClass {
    /// Generated by `attestd` locally; not suitable for remote export.
    LocalOnly = 0x01,
    /// Entered through the text proxy by a local operator.
    OperatorTyped = 0x02,
    /// Received from `secure-transportd` (v0.4 RFC 005).
    RemoteChallenge = 0x03,
}

/// Structured freshness claims for v2 (replaces the unstructured v1 nonce).
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub struct FreshnessClaimsV2 {
    pub generation: u32,
    /// Active `AttestationSigning` epoch at signing time.
    pub key_epoch: u32,
    pub status: u8,
    pub nonce_class: u8,
    /// 16-byte nonce (zero-padded if caller-supplied is shorter).
    pub nonce_bytes: [u8; 16],
}

// ── AttestationRecordV2 ──────────────────────────────────────────────────────

/// v2 attestation record — binds provider, keyring, rollback, measurement,
/// and freshness into one signed unit (RFC v0.3-004 §6.2).
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub struct AttestationRecordV2 {
    pub schema_version: u16, // = 2
    pub record_id: AttestationRecordId,
    pub created_tick: u64,
    pub profile: AttestationProfile, // = FjellLocalV2Binary
    pub provider: ProviderClaims,
    pub keyring: KeyringClaims,
    pub boot: BootClaims,
    pub verification: VerificationClaims,
    pub measurement: MeasurementClaims,
    pub snapshot: SnapshotClaims,
    pub health: HealthClaims,
    pub rollback: RollbackClaims,
    pub freshness: FreshnessClaimsV2,
    pub provenance: Option<ProvenanceClaims>,
}

impl AttestationRecordV2 {
    pub const SCHEMA_VERSION: u16 = 2;

    /// The canonical v2 byte stream (RFC v0.3-004 §6.3) — **the function the
    /// digest is computed from and the frozen schema is generated from**.
    pub fn write_canonical(&self, c: &mut dyn Canon) {
        c.domain(ATTEST_V2_DOMAIN);
        c.u16("schema_version", self.schema_version);
        c.bytes("record_id", &self.record_id.0);
        c.u64("created_tick", self.created_tick);
        c.u8("profile", self.profile as u8);
        // provider
        c.u32("provider.provider_id", self.provider.provider_id.0);
        c.u8("provider.provider_kind", self.provider.provider_kind);
        c.u8("provider.profile_tag", self.provider.profile_tag);
        c.u16(
            "provider.provider_generation",
            self.provider.provider_generation,
        );
        // keyring
        c.u32(
            "keyring.active_epoch_attestation",
            self.keyring.active_epoch_attestation,
        );
        c.u32(
            "keyring.active_epoch_release",
            self.keyring.active_epoch_release,
        );
        c.u32(
            "keyring.active_epoch_policy",
            self.keyring.active_epoch_policy,
        );
        c.bytes(
            "keyring.keyring_snapshot_digest",
            &self.keyring.keyring_snapshot_digest.0,
        );
        // boot
        c.u8("boot.selected_slot", self.boot.selected_slot);
        c.u64("boot.boot_id", self.boot.boot_id);
        c.bytes("boot.kernel_digest", &self.boot.kernel_digest.0);
        // verification
        c.bytes(
            "verification.release_digest",
            &self.verification.release_digest.0,
        );
        c.bytes(
            "verification.rootfs_digest",
            &self.verification.rootfs_digest.0,
        );
        c.bytes(
            "verification.policy_digest",
            &self.verification.policy_digest.0,
        );
        // bit 0 release_verified, bit 1 rootfs_verified, bit 2 policy_verified
        let vflags: u8 = (self.verification.release_verified as u8)
            | ((self.verification.rootfs_verified as u8) << 1)
            | ((self.verification.policy_verified as u8) << 2);
        c.u8("verification.verified_flags", vflags);
        // measurement
        c.u64("measurement.head_seq", self.measurement.head_seq);
        c.bytes("measurement.chain_digest", &self.measurement.chain_digest.0);
        c.u64(
            "measurement.included_from_seq",
            self.measurement.included_from_seq,
        );
        c.u64(
            "measurement.included_to_seq",
            self.measurement.included_to_seq,
        );
        // snapshot
        c.bytes("snapshot.snapshot_id", &self.snapshot.snapshot_id);
        c.bytes("snapshot.snapshot_digest", &self.snapshot.snapshot_digest.0);
        c.u8("snapshot.reason", self.snapshot.reason);
        // health
        c.bytes("health.target", &self.health.target);
        c.u8("health.status", self.health.status);
        // rollback
        c.bytes("rollback.channel_id", &self.rollback.channel_id);
        c.u64("rollback.min_counter", self.rollback.min_counter);
        c.u8(
            "rollback.last_advance_source",
            self.rollback.last_advance_source,
        );
        c.u8(
            "rollback.trust_provider_counter_supported",
            self.rollback.trust_provider_counter_supported as u8,
        );
        c.u64(
            "rollback.trust_provider_counter_value",
            self.rollback.trust_provider_counter_value,
        );
        // freshness
        c.u32("freshness.generation", self.freshness.generation);
        c.u32("freshness.key_epoch", self.freshness.key_epoch);
        c.u8("freshness.status", self.freshness.status);
        c.u8("freshness.nonce_class", self.freshness.nonce_class);
        c.bytes("freshness.nonce_bytes", &self.freshness.nonce_bytes);
        // provenance: a present byte, then the fields (or zeros / result 3 when absent)
        c.u8("provenance.present", self.provenance.is_some() as u8);
        c.bytes(
            "provenance.sidecar_digest",
            &self
                .provenance
                .map(|p| p.sidecar_digest.0)
                .unwrap_or([0u8; 32]),
        );
        c.u8(
            "provenance.result",
            self.provenance.map(|p| p.result).unwrap_or(3u8),
        );
    }

    /// Compute the canonical v2 digest (RFC v0.3-004 §6.3).
    pub fn canonical_digest(&self) -> Digest32 {
        let mut sink = BufSink::<{ ATTEST_V2_STREAM_MAX }>::new();
        self.write_canonical(&mut sink);
        Digest32::of(sink.bytes())
    }
}

// ── Signed envelope ──────────────────────────────────────────────────────────

/// Identifies which anchor produced the signature.
/// Not included in `record_digest`; used to locate the verification anchor.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub struct SignedByDescriptor {
    pub provider_id: TrustProviderId,
    pub provider_generation: u16,
    /// Epoch of the anchor used for signing.
    pub keyring_anchor_epoch: u32,
    /// `SignatureAlgorithm` tag.
    pub algorithm: u8,
}

/// Signed attestation v2 record envelope.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub struct SignedAttestationRecordV2 {
    pub record: AttestationRecordV2,
    pub record_digest: Digest32,
    pub signature: Signature,
    pub signed_by: SignedByDescriptor,
}

impl SignedAttestationRecordV2 {
    /// Sign a record using a `HardwareTrustProvider`.
    pub fn sign<P: HardwareTrustProvider>(
        record: AttestationRecordV2,
        provider: &P,
        signed_by: SignedByDescriptor,
    ) -> Result<Self, fjell_trust_provider::error::TrustError> {
        let digest = record.canonical_digest();
        let signature = provider.sign_attestation(AttestationDigest(digest))?;
        Ok(Self {
            record,
            record_digest: digest,
            signature,
            signed_by,
        })
    }

    /// Verify: recompute the digest and verify signature via the trust provider.
    ///
    /// Uses the same development signing path for a round-trip check.
    pub fn verify<P: HardwareTrustProvider>(&self, provider: &P) -> bool {
        let expected = self.record.canonical_digest();
        if expected != self.record_digest {
            return false;
        }
        // Re-sign the same digest and compare; works for DevelopmentTrustProvider.
        provider
            .sign_attestation(AttestationDigest(self.record_digest))
            .map(|sig| sig.as_slice() == self.signature.as_slice())
            .unwrap_or(false)
    }
}

// ── Development factory ──────────────────────────────────────────────────────

impl AttestationRecordV2 {
    /// Build a development-grade v2 record with deterministic zero-filled fields.
    pub fn dev(
        record_id: AttestationRecordId,
        provider_id: TrustProviderId,
        channel_id: [u8; 8],
        nonce_bytes: [u8; 16],
        rollback_min: u64,
        generation: u32,
    ) -> Self {
        Self {
            schema_version: Self::SCHEMA_VERSION,
            record_id,
            created_tick: 0,
            profile: AttestationProfile::FjellLocalV2Binary,
            provider: ProviderClaims {
                provider_id,
                provider_kind: TrustProviderKind::Development as u8,
                profile_tag: TrustProfile::FjellLocalV1 as u8,
                provider_generation: 1,
            },
            keyring: KeyringClaims {
                active_epoch_attestation: 1,
                active_epoch_release: 1,
                active_epoch_policy: 0,
                keyring_snapshot_digest: Digest32([0; 32]),
            },
            boot: BootClaims {
                selected_slot: 0,
                boot_id: 1,
                kernel_digest: Digest32([0x11; 32]),
            },
            verification: VerificationClaims {
                release_digest: Digest32([0x22; 32]),
                rootfs_digest: Digest32([0x33; 32]),
                policy_digest: Digest32([0x44; 32]),
                release_verified: true,
                rootfs_verified: true,
                policy_verified: true,
            },
            measurement: MeasurementClaims {
                head_seq: 1,
                chain_digest: Digest32([0x55; 32]),
                included_from_seq: 1,
                included_to_seq: 1,
            },
            snapshot: SnapshotClaims {
                snapshot_id: *b"SN000001",
                snapshot_digest: Digest32([0x66; 32]),
                reason: 0,
            },
            health: HealthClaims {
                target: *b"attestd\0",
                status: 0,
            },
            rollback: RollbackClaims {
                channel_id,
                min_counter: rollback_min,
                last_advance_source: AdvanceSource::UpgradedConfirmation as u8,
                trust_provider_counter_supported: true,
                trust_provider_counter_value: rollback_min,
            },
            freshness: FreshnessClaimsV2 {
                generation,
                key_epoch: 1,
                status: 0,
                nonce_class: NonceClass::LocalOnly as u8,
                nonce_bytes,
            },
            provenance: None,
        }
    }
}
