//! Generates the `.frozen` schema files from the encoders themselves and fails
//! when a committed file has drifted (RFC-0.33-003, E-045).
//!
//! * [`record::Recorder`] — a `Canon` sink that writes down what an encoder wrote.
//! * [`registry`] — which formats have a file, which do not and why.
//! * [`generate`] / [`compare`] — the text a format's file must hold, and the
//!   comparison that names the field when a committed file does not.
//!
//! The comparison is between **generated text and committed text**. There is no
//! parser for the `.frozen` grammar: to *name* the field that differs it splits
//! each side into lines and keys them by their first two words.

pub mod record;
pub mod registry;
pub mod samples;

use record::Recorder;
use registry::Format;
use std::collections::BTreeMap;

/// The exact text of a format's `.frozen` file, or why one cannot be made.
pub fn generate(f: &Format) -> Result<String, Vec<String>> {
    let mut r = Recorder::new();
    (f.write)(&mut r);
    if !r.problems().is_empty() {
        return Err(r.problems().to_vec());
    }
    let mut out = String::new();
    out.push_str(
        "# generated by `cargo xtask schema dump` — do not edit; the encoder is the description\n",
    );
    out.push_str(&format!("# crate: {}\n", f.krate));
    out.push_str(&format!("# format: {}\n", f.name));
    match f.on_disk {
        // The format's own version first (D11), and where the file came from beside it.
        Some(v) => out.push_str(&format!("# version: v{} on disk ({})\n", v(), f.version)),
        None => out.push_str(&format!("# version: {}\n", f.version)),
    }
    for n in f.notes {
        out.push_str(&format!("# note: {n}\n"));
    }
    out.push_str(&r.body());
    out.push_str("end\n");
    Ok(out)
}

/// One place the committed file and the encoder's output disagree.
#[derive(Clone, PartialEq, Eq, Debug)]
pub struct Drift(pub String);

impl std::fmt::Display for Drift {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(&self.0)
    }
}

/// Key a line by its first two words (its kind and its name), numbered when one
/// key repeats, so two fields with one name stay distinct. The rest of the line is
/// the value. A group's fields carry the group's name in their own (`records[].kind`),
/// so no nesting has to be tracked to tell them apart.
fn keyed(text: &str) -> Vec<(String, String)> {
    let mut out = Vec::new();
    let mut seen: BTreeMap<String, usize> = BTreeMap::new();
    for raw in text.lines() {
        let mut w = raw.split_whitespace();
        let Some(kind) = w.next() else { continue };
        // `# version: …` and `# note: …` are keyed by the word after the `#`.
        let name = w.next().unwrap_or("").trim_end_matches(':');
        let base = if name.is_empty() {
            kind.to_string()
        } else {
            format!("{kind} {name}")
        };
        let n = seen.entry(base.clone()).or_insert(0);
        *n += 1;
        let key = if *n > 1 {
            format!("{base} (#{n})")
        } else {
            base
        };
        out.push((key, w.collect::<Vec<_>>().join(" ")));
    }
    out
}

/// Compare a format's committed file with what its encoder generates. Empty means
/// the file is true. Each drift names the field.
pub fn compare(generated: &str, committed: &str) -> Vec<Drift> {
    if generated == committed {
        return vec![];
    }
    let g = keyed(generated);
    let c = keyed(committed);
    let gm: BTreeMap<&str, &str> = g.iter().map(|(k, v)| (k.as_str(), v.as_str())).collect();
    let cm: BTreeMap<&str, &str> = c.iter().map(|(k, v)| (k.as_str(), v.as_str())).collect();
    let mut out = Vec::new();
    for (k, v) in &c {
        match gm.get(k.as_str()) {
            None => out.push(Drift(format!(
                "`{k}` is in the committed file (`{v}`) but the encoder does not write it"
            ))),
            Some(gv) if gv != v => out.push(Drift(format!(
                "`{k}`: the committed file says `{v}`, the encoder writes `{gv}`"
            ))),
            Some(_) => {}
        }
    }
    for (k, v) in &g {
        if !cm.contains_key(k.as_str()) {
            out.push(Drift(format!(
                "`{k}` (`{v}`) is written by the encoder but absent from the committed file"
            )));
        }
    }
    if out.is_empty() {
        // Same keys, same values, so only the order (or a whitespace-only) differs.
        let pos = g.iter().zip(&c).position(|(a, b)| a.0 != b.0);
        out.push(Drift(match pos {
            Some(i) => format!(
                "field order differs: line {} is `{}` in the committed file and `{}` in the encoder's output",
                i + 1,
                c[i].0,
                g[i].0
            ),
            None => "the committed file differs from the encoder's output only in formatting".into(),
        }));
    }
    out
}
