[package]
name = "fjell-syncd"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
publish = false

[[bin]]
name = "fjell-syncd"
path = "src/main.rs"

[dependencies]
fjell-abi      = { path = "../../fjell-abi" }
fjell-syscall  = { path = "../../fjell-syscall" }
fjell-snapshot-format  = { path = "../../formats/fjell-snapshot-format" }
fjell-identity-format  = { path = "../../formats/fjell-identity-format" }
fjell-measure-format   = { path = "../../formats/fjell-measure-format" }
